In [1]:
import torch

In [3]:
torch.cuda.is_available()

True

# *Tensor*

In [11]:
def describe(x):
    print("타입 : {}".format(x.type()))
    print("크기: {}".format(x.shape))
    print("값: \n{}".format(x))

### *랜덤 텐서 초기화*

In [12]:
tensor = torch.Tensor(2, 3)
describe(tensor)

타입 : torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[ 1.5280e-36,  0.0000e+00, -8.4576e-15],
        [ 4.5733e-41,  8.9683e-44,  0.0000e+00]])


### *균등 분포 랜덤 텐서*

In [13]:
tensor = torch.rand(2, 3)
describe(tensor)

타입 : torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[0.2888, 0.3199, 0.1762],
        [0.7914, 0.9894, 0.5572]])


### *표준 정규 분포 랜덤 텐서*

In [14]:
tensor = torch.randn(2, 3)
describe(tensor)

타입 : torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[ 0.1120, -0.0568,  0.6444],
        [-1.6637,  0.0071, -0.9954]])


### *fill_()*

In [16]:
# 0 채우기
tensor = torch.zeros(2, 3)
describe(tensor)

타입 : torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [18]:
# 1 채우기
tensor = torch.ones(2, 3)
describe(tensor)

타입 : torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [19]:
tensor = tensor.fill_(5)
describe(tensor)

타입 : torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[5., 5., 5.],
        [5., 5., 5.]])


# 

### *List to Tensor*

In [22]:
import numpy as np

In [21]:
li = [[2, 3, 4], [5, 6, 7]]
x = torch.Tensor(li)
describe(x)

타입 : torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[2., 3., 4.],
        [5., 6., 7.]])


### *Numpy to Tensor*
##### numpy 배열을 사용하면 텐서 타입이 기본 FloatTensor가 아니라 DoubleTensor가 됨.

In [24]:
npy = np.random.rand(2, 3)
describe(torch.from_numpy(npy))

타입 : torch.DoubleTensor
크기: torch.Size([2, 3])
값: 
tensor([[0.0886, 0.9384, 0.3761],
        [0.3845, 0.5054, 0.7658]], dtype=torch.float64)


# 

### *Tensor type shape*