In [1]:
import torch

In [2]:
torch.cuda.is_available()

True

# *Tensor*

In [3]:
def describe(x):
    print("타입 : {}".format(x.type()))
    print("크기: {}".format(x.shape))
    print("값: \n{}".format(x))

### *랜덤 텐서 초기화*

In [4]:
tensor = torch.Tensor(2, 3)
describe(tensor)

타입 : torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[ 2.4697e+03,  4.5839e-41,  1.2227e+15],
        [-4.1812e+26,  4.9780e+04,  4.5839e-41]])


### *균등 분포 랜덤 텐서*

In [5]:
tensor = torch.rand(2, 3)
describe(tensor)

타입 : torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[0.5250, 0.1546, 0.3809],
        [0.0429, 0.3662, 0.3237]])


### *표준 정규 분포 랜덤 텐서*

In [6]:
tensor = torch.randn(2, 3)
describe(tensor)

타입 : torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[-0.1303, -1.5500, -1.1097],
        [-0.0259,  0.8308,  0.7508]])


### *fill_()*

In [7]:
# 0 채우기
tensor = torch.zeros(2, 3)
describe(tensor)

타입 : torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [8]:
# 1 채우기
tensor = torch.ones(2, 3)
describe(tensor)

타입 : torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [9]:
tensor = tensor.fill_(5)
describe(tensor)

타입 : torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[5., 5., 5.],
        [5., 5., 5.]])


# 

### *List to Tensor*

In [10]:
import numpy as np

In [11]:
li = [[2, 3, 4], [5, 6, 7]]
x = torch.Tensor(li)
describe(x)

타입 : torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[2., 3., 4.],
        [5., 6., 7.]])


### *Numpy to Tensor*
##### numpy 배열을 사용하면 텐서 타입이 기본 FloatTensor가 아니라 DoubleTensor가 됨.

In [12]:
npy = np.random.rand(2, 3)
describe(torch.from_numpy(npy))

타입 : torch.DoubleTensor
크기: torch.Size([2, 3])
값: 
tensor([[0.3427, 0.2952, 0.0955],
        [0.0877, 0.7238, 0.6975]], dtype=torch.float64)


# 

### *Tensor type shape*

##### *기본 텐서 타입 torch.FloatTensor*

In [13]:
li = [[1, 2, 3],
[4, 5, 6]]

In [14]:
x = torch.Tensor(li)
describe(x)

타입 : torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [15]:
x1 = torch.FloatTensor(li)
describe(x1)

타입 : torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [16]:
x1 = x1.long()
describe(x1)

타입 : torch.LongTensor
크기: torch.Size([2, 3])
값: 
tensor([[1, 2, 3],
        [4, 5, 6]])


In [17]:
x2 = torch.tensor(li, dtype=torch.int64)
describe(x2)

타입 : torch.LongTensor
크기: torch.Size([2, 3])
값: 
tensor([[1, 2, 3],
        [4, 5, 6]])


In [18]:
x2 = x2.float()
describe(x2)

타입 : torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


# 

### *Tensor Calculation*

In [19]:
x = torch.randn(2, 3)
describe(x)

타입 : torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[-0.7083, -1.5506, -0.0478],
        [ 0.4651, -1.1413,  0.3482]])


In [24]:
describe(torch.add(x, x))
describe(x + x)

타입 : torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[-1.4165, -3.1012, -0.0955],
        [ 0.9302, -2.2826,  0.6963]])
타입 : torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[-1.4165, -3.1012, -0.0955],
        [ 0.9302, -2.2826,  0.6963]])


In [25]:
describe(torch.add(x, 3))
describe(x + 3)

타입 : torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[2.2917, 1.4494, 2.9522],
        [3.4651, 1.8587, 3.3482]])
타입 : torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[2.2917, 1.4494, 2.9522],
        [3.4651, 1.8587, 3.3482]])


# 

### *Tensor 차원 변경*

In [27]:
x = torch.arange(6)
describe(x)

타입 : torch.LongTensor
크기: torch.Size([6])
값: 
tensor([0, 1, 2, 3, 4, 5])


In [29]:
x = x.view(2, 3)
describe(x)

타입 : torch.LongTensor
크기: torch.Size([2, 3])
값: 
tensor([[0, 1, 2],
        [3, 4, 5]])


In [34]:
describe(torch.sum(x, dim=0))

타입 : torch.LongTensor
크기: torch.Size([3])
값: 
tensor([3, 5, 7])


In [31]:
describe(torch.sum(x, dim=1))

타입 : torch.LongTensor
크기: torch.Size([2])
값: 
tensor([ 3, 12])


In [32]:
describe(torch.transpose(x, 0, 1))

타입 : torch.LongTensor
크기: torch.Size([3, 2])
값: 
tensor([[0, 3],
        [1, 4],
        [2, 5]])


# 

### *index, slicing, match*

In [39]:
x = torch.arange(6).view(2, 3)
describe(x)

타입 : torch.LongTensor
크기: torch.Size([2, 3])
값: 
tensor([[0, 1, 2],
        [3, 4, 5]])


In [45]:
describe(x[:1, :2])

타입 : torch.LongTensor
크기: torch.Size([1, 2])
값: 
tensor([[0, 1]])


In [48]:
describe(x[0, 1])

타입 : torch.LongTensor
크기: torch.Size([])
값: 
1


##### *복잡한 인덱싱, 연속적이지 않은 텐서 인덱스 참조*
##### *index_select() 함수가 반환하는 텐서는 dim 매개변수에 지정한 차원의 크기가 index 매개변수에 지정한 텐서 길이와 같음*

In [6]:
x = torch.arange(6).view(2, 3)
describe(x)

타입 : torch.LongTensor
크기: torch.Size([2, 3])
값: 
tensor([[0, 1, 2],
        [3, 4, 5]])


In [7]:
indices = torch.LongTensor([0, 2])
print(f"indices : {indices}")
describe(torch.index_select(x, dim=1, index=indices))

indices : tensor([0, 2])
타입 : torch.LongTensor
크기: torch.Size([2, 2])
값: 
tensor([[0, 2],
        [3, 5]])


In [9]:
indices = torch.LongTensor([0, 0])
describe(torch.index_select(x, dim=0, index=indices))

타입 : torch.LongTensor
크기: torch.Size([2, 3])
값: 
tensor([[0, 1, 2],
        [0, 1, 2]])


In [11]:
row_indices = torch.arange(2).long()
print(f"row_indices : {row_indices}")

col_indices = torch.LongTensor([0, 1])
print(f"col_indices : {col_indices}")

describe(x[row_indices, col_indices])

row_indices : tensor([0, 1])
col_indices : tensor([0, 1])
타입 : torch.LongTensor
크기: torch.Size([2])
값: 
tensor([0, 4])


##### *텐서 연결*

In [12]:
x = torch.arange(6).view(2, 3)
describe(x)

타입 : torch.LongTensor
크기: torch.Size([2, 3])
값: 
tensor([[0, 1, 2],
        [3, 4, 5]])


In [13]:
describe(torch.cat([x, x], dim=0))

타입 : torch.LongTensor
크기: torch.Size([4, 3])
값: 
tensor([[0, 1, 2],
        [3, 4, 5],
        [0, 1, 2],
        [3, 4, 5]])


In [14]:
describe(torch.cat([x, x], dim=1))

타입 : torch.LongTensor
크기: torch.Size([2, 6])
값: 
tensor([[0, 1, 2, 0, 1, 2],
        [3, 4, 5, 3, 4, 5]])


In [15]:
describe(torch.stack([x, x]))

타입 : torch.LongTensor
크기: torch.Size([2, 2, 3])
값: 
tensor([[[0, 1, 2],
         [3, 4, 5]],

        [[0, 1, 2],
         [3, 4, 5]]])


##### *텐서 선형대수 계산*

In [23]:
# 행렬 곱셉 mm
x1 = torch.arange(6).view(2, 3).float()
describe(x1)

x2 = torch.ones(3, 2)
x2[:, 1] += 1
describe(x2)

describe(torch.mm(x1, x2))

타입 : torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[0., 1., 2.],
        [3., 4., 5.]])
타입 : torch.FloatTensor
크기: torch.Size([3, 2])
값: 
tensor([[1., 2.],
        [1., 2.],
        [1., 2.]])
타입 : torch.FloatTensor
크기: torch.Size([2, 2])
값: 
tensor([[ 3.,  6.],
        [12., 24.]])
